[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "importer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kaesar-import"
path = "src/main.rs"

[dependencies]
kaesar-core = { path = "../core" }
getopts = "0.2.24"
